server:
  port: 8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: sms-service:8004
    prefer-ip-address: true

spring:
  application:
    name: sms-service
