server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: cache-service:8002
    prefer-ip-address: true

spring:
  application:
    name: cache-service
