server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: file-service:8001
    prefer-ip-address: true

spring:
  application:
    name: file-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240000  #单个文件的最大上限
      max-request-size: 10240000 #单个请求的文件总大小上限
