server:
  port: 9002

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///hrm-course?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
      name: course-service

#eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册的地址
  instance:
    instance-id: course-service:9002
    prefer-ip-address: true

logging:
  level:
    cn.itsource.hrm.mapper: debug
hrm:
  swagger:
    title: 课程服务
    description: 课程服务接口描述

feign:
   hystrix:
       enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000